version: "3.9"
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"
  php-seed:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /app
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true idekey=idea mode=debug start_with_request=yes'
    depends_on:
      - db
    command: php /app/seed.php
    restart: "no"
  php-check:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /app
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true idekey=idea mode=debug start_with_request=yes'
    depends_on:
      - db
    command: php /app/check-emails.php
    restart: always
  php-notify:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /app
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true idekey=idea mode=debug start_with_request=yes'
    depends_on:
      - db
    command: php /app/send-notifcations.php
    restart: always
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.2.2.0/24
